name: CI
on: 
  push:
    branches:
      - "main"

jobs:
  Git_Pull:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /var/www/udify_mongo/udify-mongo
    steps:
      - name: add directory into safe 
        run: git config --global --add safe.directory /var/www/udify_mongo/udify-mongo
      - name: Taking Git Pull
        run: GIT_SSH_COMMAND='ssh -i ~/.ssh/mongo' git pull

  Build:
    needs: Git_Pull
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /var/www/udify_mongo/udify-mongo
    steps:
      - name: Install dependencies
        run: npm install 


  Deploy_Image:
    needs: Build 
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /var/www/udify_mongo/udify-mongo
    steps:
      - name: Deploy the code
        run: pm2 reload 0
